make re
./fillit map/tetri_error
./fillit map/tetri_error2
./fillit map/tetri_error3
./fillit map/tetri_error4
./fillit map/tetri_error5
./fillit map/tetri_error6
./fillit map/tetri_error7
./fillit map/tetri_error8
./fillit map/tetri_error9
./fillit map/tetri_error10
./fillit map/tetri_error11
./fillit map/tetri_error12
./fillit map/tetri_error13
./fillit map/tetri_error14
./fillit map/tetri_error15
./fillit map/tetri_error16
./fillit map/tetri_error17
./fillit map/tetri_error18
./fillit map/tetri1
./fillit map/tetriminos
